export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { prompt } = req.body
  if (!prompt) {
    return res.status(400).json({ error: 'Missing prompt' })
  }

  // Mock response for study purposes
  const mockResponse = `This is a mock response for: ${prompt}. In a real implementation, this would be generated by Ollama or another AI service.`

  // For streaming, simulate
  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')

  const words = mockResponse.split(' ')
  let index = 0

  const interval = setInterval(() => {
    if (index < words.length) {
      res.write(`data: ${words[index]} \n\n`)
      index++
    } else {
      res.write('event: end\ndata: END\n\n')
      res.end()
      clearInterval(interval)
    }
  }, 100) // Send a word every 100ms
}
