export default function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { prompt } = req.body
  if (!prompt) {
    return res.status(400).json({ error: 'Missing prompt' })
  }

  // Mock story response
  const mockText = `Mock Story Title

Introduction: Once upon a time in a mock world...

Body: The story would unfold here with characters and plot, generated by AI.

Conclusion: And they lived happily ever after. (Mock ending)`

  res.status(200).json({ text: mockText })
}
